import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Placeholder Firebase configuration.
///
/// Replace this file with one generated by the FlutterFire CLI to hook the app
/// to your Firebase project. Until then, Firebase initialization will attempt
/// to proceed without explicit options and will no-op if not configured.
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return null;
    }
    return null;
  }
}

